# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: MARS2 2025 Challenge on Multimodal Reasoning-Track 1 (for evaluation)
short_description: MRC-Track 1
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: For different tracks, please refer to the evaluation tab for their selected metrics.
evaluation_script: evaluation_script.zip
remote_evaluation: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True
tags: 
  - deep-learning
  - computer-vision
  - multimodal
  - scene understanding reasoning
leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Metric1", "Metric2", "Metric3", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Metric1": {
            "sort_ascending": False,
          },
          "Metric2": {
            "sort_ascending": False,
          }
        }
      }

challenge_phases:
  - id: 1
    name: VG-RS
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-06-01 00:00:00
    end_date: 2099-05-31 23:59:59
    test_annotation_file: annotations/VG_RS_testsplit.json
    codename: VG-RS
    max_submissions_per_day: 15
    max_submissions_per_month: 450
    max_submissions: 450
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 6
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True


